name: "GHAS to JIRA Test"

on:
  workflow_dispatch:
  push:
    branches:
      - main
#  schedule:
#    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes

jobs:
  test_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with JIRA
        uses: cmboling/lgtm-issue-tracker-example@v2
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          jira_url: '${{ secrets.JIRA_URL }}'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: '${{ secrets.JIRA_PROJECT }}'
          sync_direction: 'gh2jira'
