name: "GHAS to JIRA Test"

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with JIRA
        uses: johnlugton/lgtm-issue-tracker-example@action
        with:
          github_token: 'daa71b7c4b43fab135c0ac2bac09540e4ef3d4f7}'
          jira_url: 'https://jira.demo-stack.com'
          jira_user: 'cmboling'
          jira_token: '4?aGgPiTSW7'
          jira_project: 'GHAS2JIRA'
          sync_direction: 'gh2jira'
